site_name: 厦门大学·RoboMaster·软件标准化
site_favicon: favicon.ico
site_url: 
nav:
- Overview:
    - Introduction: Introduction.md
    - Hardware Support: Hardware-Support.md
- Beginners:
    - Software Install: Software-Install.md
    - Getting Started: Getting-Started.md
    - TIM: TIM-Use.md
    - USART: USART-Use.md
    - CAN: CAN-Use.md
- Algorithms:
    - Motor Control: Motor-Control.md
- Livox Mid-70:
    - Development Guide: Livox-Mid70-Guidance.md
- References:
    - Motor Parameters: Motor-Parameters.md
- FAQs:
    - How to Debug: How-to-Debug.md

    
theme: mkdocs
site_author: ASR-Crash
copyright: Copyright © 2021 ASR-Crash, Mike.Han, R.P.Su